import Navbar from "./components/Navbar";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll"; // Importamos el nuevo componente
import { ViewTransitions } from "next-view-transitions";

export const metadata = {
  title: "ARTENUEVO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="es">
        <body>
          <main>
            <SmoothScroll />
            <Navbar />
            {children}
          </main>
        </body>
      </html>
    </ViewTransitions>
  );
}
