import Navbar from "./components/Navbar";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll"; // Importamos el nuevo componente
import Proyectos from "./components/Proyectos";
import Footer from "./components/Footer";
import TotalScroll from "./components/TotalScroll";

export const metadata = {
  title: "ARTENUEVO",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const res = await fetch(`${process.env.WP_API_URL}/portfolio?_embed=true`, {
    cache: "force-cache",
    next: { revalidate: 60 }, // Se actualiza cada 60 seg
  });

  const data = await res.json();
  return (
    <html lang="es">
      <body>
        <main>
          <SmoothScroll />
          <Navbar />
          {/* <TotalScroll /> */}
          <Proyectos data={data} />
          <Footer />
          {children}
        </main>
      </body>
    </html>
  );
}
